You only throw an exception if you want it to be handled by a "higher" function.
 So, the `main` method should not throw an exception, you should handle it.
 
 [Source](https://stackoverflow.com/questions/17629321/throwing-exception-in-main-method)